version: '3.5'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - dbvolume:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_app
    restart: always
    ports:
      - "9090:8080"

  discovery-service:
    build: ./discovery-service
    networks:
      - backend
    ports:
      - 8082:8082

  gateway-service:
    build: ./gateway-service
    depends_on:
      - postgres_db
    networks:
      - backend
    ports:
      - 8083:8083

  order-service:
    build: ./order-service
    depends_on:
      - discovery-service
      - rabbitmq
      - postgres_db
      - gateway-service
    networks:
      - backend
    ports:
      - 8084:8084





networks:
  backend:
    driver: bridge

volumes:
  dbvolume:
    external: false
