
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
    register-with-eureka: true
    fetch-registry: true
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: 8083

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

management:
  endpoint:
    gateway:
      enabled: true
    loggers:
      enabled: true
    info:
      enable: on
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: gateway
