server:
  port: 8084
  servlet:
    context-path: /cms
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cms
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
    enabled: false